[package]
name = "musika"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.10.3"
libadwaita = "0.8.1"
glib = "0.21.2"
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
serde_json = "1.0.128"
rusqlite = { version = "0.33", features = ["bundled"] }
